# shell /bin/zsh

# Fonts
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12

# Window
confirm_os_window_close 0
window_padding_width 15

# Background
background_opacity 0.70
background_blur 1