# ----------------- hyprland conf -------------------------------

# NVIDIA
# env = LIBVA_DRIVER_NAME,nvidia
# env = XDG_SESSION_TYPE,wayland
# env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Cursor
# env = XCURSOR_THEME,NAME
# env = XCURSOR_SIZE,SIZE

# Imports conf

# Monitor
source = ~/.config/hypr/conf/monitor.conf

# Autostart
source = ~/.config/hypr/conf/autostart.conf

# Keyboard binds
source = ~/.config/hypr/conf/bind.conf

# Keyboard
source = ~/.config/hypr/conf/keyboard.conf

# Animation
source = ~/.config/hypr/conf/animation.conf

# Window rules
source = ~/.config/hypr/conf/windowrules.conf

# ---------------------------------------------------------------