# -----------------------------------------------------------

# Appearance of windows

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(c0caf5ee)
    col.inactive_border = rgba(1a1b26aa)
}

decoration {
    rounding = 15
    blur {
        enabled = true
        size = 7
        passes = 3
        ignore_opacity = true
        new_optimizations = true

        noise = 0.08
        contrast = 1.5
        xray = false
    }
}

# -----------------------------------------------------------